# Generated by Django 3.0 on 2019-12-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='preview',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
