# Generated by Django 3.0 on 2019-12-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_feedback_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='preview',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(),
        ),
    ]
